version: '3.7'

services:
    php:
        image: php:8-alpine
        working_dir: /var/www
        command: /bin/sh -c "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\" && php composer-setup.php && php -S 0.0.0.0:80 -t public"
        ports:
            - 80:80
        volumes:
            - .:/var/www
